import type { Job, Quote, SystemSettings } from '../types';

// ── Shared PDF Utilities ──

function companyHeader(s: SystemSettings): string {
  return `
    <div style="display:flex;align-items:center;gap:16px;margin-bottom:20px;padding-bottom:16px;border-bottom:2px solid #e5e7eb">
      ${s.companyLogo ? `<img src="${s.companyLogo}" style="height:48px;width:auto;object-fit:contain" />` : ''}
      <div>
        <div style="font-size:20px;font-weight:800;color:#111">${s.companyName || 'Company Name'}</div>
        ${s.companyAddress ? `<div style="font-size:11px;color:#6b7280">${s.companyAddress}</div>` : ''}
        ${s.companyPhone ? `<div style="font-size:11px;color:#6b7280">${s.companyPhone}</div>` : ''}
      </div>
    </div>`;
}

function docFooter(): string {
  return `<div style="margin-top:40px;padding-top:12px;border-top:1px solid #e5e7eb;text-align:center;font-size:9px;color:#9ca3af">Generated by SC Tracker &mdash; ${new Date().toLocaleString()}</div>`;
}

function openPrintWindow(html: string, title: string) {
  const win = window.open('', '_blank', 'width=800,height=1000');
  if (!win) return;
  win.document.write(`<!DOCTYPE html><html><head><title>${title}</title>
    <style>
      * { margin:0; padding:0; box-sizing:border-box; }
      body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding:40px; color:#111; background:#fff; font-size:13px; line-height:1.5; }
      table { width:100%; border-collapse:collapse; margin:12px 0; }
      th { text-align:left; padding:8px 12px; background:#f3f4f6; font-size:10px; text-transform:uppercase; letter-spacing:0.05em; color:#6b7280; font-weight:700; border-bottom:2px solid #e5e7eb; }
      td { padding:8px 12px; border-bottom:1px solid #f3f4f6; }
      .badge { display:inline-block; padding:2px 8px; border-radius:4px; font-size:10px; font-weight:700; }
      .sig-line { margin-top:60px; display:flex; gap:40px; }
      .sig-line > div { flex:1; padding-top:8px; border-top:1px solid #111; font-size:10px; color:#6b7280; }
      @media print { body { padding:20px; } }
    </style>
  </head><body>${html}</body></html>`);
  win.document.close();
  setTimeout(() => { win.print(); }, 300);
}

// ── Quote PDF ──

export function printQuotePDF(quote: Quote, settings: SystemSettings) {
  const html = `
    ${companyHeader(settings)}
    <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px">
      <div>
        <div style="font-size:24px;font-weight:800;color:#111">QUOTE</div>
        <div style="font-size:14px;color:#6b7280;margin-top:2px">${quote.quoteNumber}</div>
      </div>
      <div style="text-align:right">
        <div style="font-size:12px;color:#6b7280">Date: ${new Date(quote.createdAt).toLocaleDateString()}</div>
        ${quote.validUntil ? `<div style="font-size:12px;color:#6b7280">Valid Until: ${quote.validUntil}</div>` : ''}
        <div class="badge" style="margin-top:6px;background:${quote.status === 'accepted' ? '#dcfce7;color:#166534' : quote.status === 'sent' ? '#dbeafe;color:#1e40af' : '#f3f4f6;color:#374151'}">${quote.status.toUpperCase()}</div>
      </div>
    </div>
    ${quote.jobDescription ? `<div style="margin-bottom:16px;padding:12px;background:#f0f9ff;border:1px solid #bae6fd;border-radius:8px"><div style="font-size:10px;text-transform:uppercase;color:#0369a1;font-weight:700;margin-bottom:4px">Scope of Work</div><div style="font-size:12px;color:#0c4a6e">${quote.jobDescription}</div></div>` : ''}
    <div style="display:grid;grid-template-columns:${quote.shipTo?.name ? '1fr 1fr' : '1fr'};gap:16px;margin-bottom:20px">
      <div style="padding:12px;background:#f9fafb;border-radius:8px;border:1px solid #e5e7eb">
        <div style="font-size:10px;text-transform:uppercase;color:#9ca3af;font-weight:700;margin-bottom:4px">Bill To</div>
        <div style="font-size:15px;font-weight:700">${quote.billTo?.name || quote.customer}</div>
        ${quote.billTo?.contactPerson ? `<div style="font-size:12px;color:#6b7280">${quote.billTo.contactPerson}</div>` : ''}
        ${quote.billTo?.email ? `<div style="font-size:12px;color:#6b7280">${quote.billTo.email}</div>` : ''}
        ${quote.billTo?.phone ? `<div style="font-size:12px;color:#6b7280">${quote.billTo.phone}</div>` : ''}
        ${quote.billTo?.address ? `<div style="font-size:11px;color:#9ca3af;margin-top:4px">${quote.billTo.address}</div>` : ''}
      </div>
      ${quote.shipTo?.name ? `<div style="padding:12px;background:#f9fafb;border-radius:8px;border:1px solid #e5e7eb">
        <div style="font-size:10px;text-transform:uppercase;color:#9ca3af;font-weight:700;margin-bottom:4px">Ship To</div>
        <div style="font-size:15px;font-weight:700">${quote.shipTo.name}</div>
        ${quote.shipTo.contactPerson ? `<div style="font-size:12px;color:#6b7280">${quote.shipTo.contactPerson}</div>` : ''}
        ${quote.shipTo.address ? `<div style="font-size:11px;color:#9ca3af;margin-top:4px">${quote.shipTo.address}</div>` : ''}
      </div>` : ''}
    </div>
    <table>
      <thead><tr><th>Description</th><th style="text-align:center">Qty</th><th style="text-align:center">Unit</th><th style="text-align:right">Rate</th><th style="text-align:right">Amount</th></tr></thead>
      <tbody>
        ${quote.items.map((item, i) => `<tr style="background:${i % 2 === 0 ? '#fff' : '#fafafa'}"><td>${item.description}</td><td style="text-align:center">${item.qty}</td><td style="text-align:center;color:#6b7280">${item.unit || 'ea'}</td><td style="text-align:right">$${item.unitPrice.toFixed(2)}</td><td style="text-align:right;font-weight:600">$${item.total.toFixed(2)}</td></tr>`).join('')}
      </tbody>
    </table>
    <div style="display:flex;justify-content:flex-end;margin-top:16px">
      <div style="width:260px">
        <div style="display:flex;justify-content:space-between;padding:6px 0;font-size:12px"><span style="color:#6b7280">Subtotal</span><span>$${quote.subtotal.toFixed(2)}</span></div>
        ${quote.markupPct ? `<div style="display:flex;justify-content:space-between;padding:6px 0;font-size:12px"><span style="color:#6b7280">Markup (${quote.markupPct}%)</span><span>+$${(quote.subtotal * quote.markupPct / 100).toFixed(2)}</span></div>` : ''}
        ${quote.discountAmt ? `<div style="display:flex;justify-content:space-between;padding:6px 0;font-size:12px"><span style="color:#6b7280">Discount (${quote.discountPct || 0}%)</span><span style="color:#dc2626">-$${quote.discountAmt.toFixed(2)}</span></div>` : ''}
        ${quote.taxAmt ? `<div style="display:flex;justify-content:space-between;padding:6px 0;font-size:12px"><span style="color:#6b7280">Tax (${quote.taxRate || 0}%)</span><span>+$${quote.taxAmt.toFixed(2)}</span></div>` : ''}
        <div style="display:flex;justify-content:space-between;padding:10px 0;font-size:18px;font-weight:800;border-top:2px solid #111;margin-top:6px"><span>Total</span><span>$${quote.total.toFixed(2)}</span></div>
        ${quote.depositRequired && quote.depositAmt ? `<div style="display:flex;justify-content:space-between;padding:6px 0;font-size:12px;color:#0891b2;font-weight:600"><span>Deposit Due (${quote.depositPct || 50}%)</span><span>$${quote.depositAmt.toFixed(2)}</span></div>` : ''}
      </div>
    </div>
    ${quote.notes ? `<div style="margin-top:24px;padding:12px;background:#fffbeb;border:1px solid #fde68a;border-radius:8px"><div style="font-size:10px;text-transform:uppercase;color:#92400e;font-weight:700;margin-bottom:4px">Notes</div><div style="font-size:12px;color:#451a03">${quote.notes}</div></div>` : ''}
    ${quote.terms ? `<div style="margin-top:12px;padding:12px;background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px"><div style="font-size:10px;text-transform:uppercase;color:#6b7280;font-weight:700;margin-bottom:4px">Terms & Conditions</div><div style="font-size:11px;color:#374151">${quote.terms}</div></div>` : ''}
    ${docFooter()}`;
  openPrintWindow(html, `Quote ${quote.quoteNumber}`);
}

// ── Packing Slip PDF ──

export function printPackingSlipPDF(job: Job, settings: SystemSettings) {
  const html = `
    ${companyHeader(settings)}
    <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px">
      <div>
        <div style="font-size:24px;font-weight:800;color:#111">PACKING SLIP</div>
      </div>
      <div style="text-align:right">
        <div style="font-size:12px;color:#6b7280">Date: ${job.shippedAt ? new Date(job.shippedAt).toLocaleDateString() : new Date().toLocaleDateString()}</div>
        <div style="font-size:12px;color:#6b7280">PO: ${job.poNumber}</div>
      </div>
    </div>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:24px">
      <div style="padding:12px;background:#f9fafb;border-radius:8px;border:1px solid #e5e7eb">
        <div style="font-size:10px;text-transform:uppercase;color:#9ca3af;font-weight:700;margin-bottom:4px">Ship To</div>
        <div style="font-size:15px;font-weight:700">${job.customer || 'Customer'}</div>
      </div>
      <div style="padding:12px;background:#f9fafb;border-radius:8px;border:1px solid #e5e7eb">
        <div style="font-size:10px;text-transform:uppercase;color:#9ca3af;font-weight:700;margin-bottom:4px">Ship Method</div>
        <div style="font-size:14px;font-weight:600">${job.shippingMethod || 'N/A'}</div>
        ${job.trackingNumber ? `<div style="font-size:12px;color:#6b7280;margin-top:2px">Tracking: ${job.trackingNumber}</div>` : ''}
      </div>
    </div>
    <table>
      <thead><tr><th>PO Number</th><th>Part Number</th><th style="text-align:right">Quantity</th><th>Description</th></tr></thead>
      <tbody>
        <tr><td style="font-weight:700">${job.poNumber}</td><td>${job.partNumber}</td><td style="text-align:right;font-weight:600">${job.quantity}</td><td style="color:#6b7280">${job.info || '-'}</td></tr>
      </tbody>
    </table>
    ${job.specialInstructions ? `<div style="margin-top:16px;padding:12px;background:#fef3c7;border:1px solid #fde68a;border-radius:8px"><div style="font-size:10px;text-transform:uppercase;color:#92400e;font-weight:700;margin-bottom:4px">Special Instructions</div><div style="font-size:12px;color:#451a03">${job.specialInstructions}</div></div>` : ''}
    ${job.shippingNotes ? `<div style="margin-top:12px;padding:12px;background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px"><div style="font-size:10px;text-transform:uppercase;color:#6b7280;font-weight:700;margin-bottom:4px">Shipping Notes</div><div style="font-size:12px">${job.shippingNotes}</div></div>` : ''}
    <div class="sig-line">
      <div>Packed By</div>
      <div>Date</div>
      <div>Received By</div>
    </div>
    ${docFooter()}`;
  openPrintWindow(html, `Packing Slip - ${job.poNumber}`);
}

// ── Job Traveler PDF ──

export function printJobTravelerPDF(job: Job, settings: SystemSettings) {
  const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${encodeURIComponent(job.id)}`;
  const html = `
    ${companyHeader(settings)}
    <div style="text-align:center;margin-bottom:24px">
      <div style="font-size:28px;font-weight:800;color:#111">PRODUCTION TRAVELER</div>
    </div>
    <div style="display:flex;gap:20px;margin-bottom:20px">
      <div style="flex:1">
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px">
          <div style="padding:12px;background:#f3f4f6;border-radius:8px">
            <div style="font-size:10px;text-transform:uppercase;color:#9ca3af;font-weight:700">PO Number</div>
            <div style="font-size:18px;font-weight:800;margin-top:4px">${job.poNumber}</div>
          </div>
          <div style="padding:12px;background:#f3f4f6;border-radius:8px">
            <div style="font-size:10px;text-transform:uppercase;color:#9ca3af;font-weight:700">Part Number</div>
            <div style="font-size:14px;font-weight:700;margin-top:4px">${job.partNumber}</div>
          </div>
          <div style="padding:12px;background:#f3f4f6;border-radius:8px">
            <div style="font-size:10px;text-transform:uppercase;color:#9ca3af;font-weight:700">Quantity</div>
            <div style="font-size:18px;font-weight:800;margin-top:4px">${job.quantity}</div>
          </div>
          <div style="padding:12px;background:#f3f4f6;border-radius:8px">
            <div style="font-size:10px;text-transform:uppercase;color:#9ca3af;font-weight:700">Due Date</div>
            <div style="font-size:14px;font-weight:700;margin-top:4px;${job.dueDate ? 'color:#dc2626' : ''}">${job.dueDate || 'N/A'}</div>
          </div>
          <div style="padding:12px;background:#f3f4f6;border-radius:8px">
            <div style="font-size:10px;text-transform:uppercase;color:#9ca3af;font-weight:700">Customer</div>
            <div style="font-size:14px;font-weight:700;margin-top:4px">${job.customer || 'N/A'}</div>
          </div>
          <div style="padding:12px;background:#f3f4f6;border-radius:8px">
            <div style="font-size:10px;text-transform:uppercase;color:#9ca3af;font-weight:700">Date Received</div>
            <div style="font-size:14px;font-weight:700;margin-top:4px">${job.dateReceived || 'N/A'}</div>
          </div>
        </div>
      </div>
      <div style="text-align:center">
        ${job.partImage ? `<img src="${job.partImage}" style="width:140px;height:100px;object-fit:cover;border-radius:8px;border:1px solid #e5e7eb;margin-bottom:8px" />` : ''}
        <img src="${qrUrl}" style="width:100px;height:100px" />
        <div style="font-size:9px;color:#9ca3af;margin-top:4px">${job.jobIdsDisplay}</div>
      </div>
    </div>
    ${job.specialInstructions ? `<div style="padding:12px;background:#fef3c7;border:1px solid #fde68a;border-radius:8px;margin-bottom:16px"><div style="font-size:10px;text-transform:uppercase;color:#92400e;font-weight:700;margin-bottom:4px">Special Instructions</div><div style="font-size:12px;color:#451a03">${job.specialInstructions}</div></div>` : ''}
    ${job.info ? `<div style="padding:12px;background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;margin-bottom:16px"><div style="font-size:10px;text-transform:uppercase;color:#6b7280;font-weight:700;margin-bottom:4px">Notes</div><div style="font-size:12px">${job.info}</div></div>` : ''}
    <div style="margin-top:20px">
      <div style="font-size:10px;text-transform:uppercase;color:#9ca3af;font-weight:700;margin-bottom:8px">Operation Log</div>
      <table>
        <thead><tr><th>Operation</th><th>Operator</th><th>Start</th><th>End</th><th>Duration</th><th>Notes</th></tr></thead>
        <tbody>
          ${[1,2,3,4,5,6].map(() => '<tr><td style="height:28px"></td><td></td><td></td><td></td><td></td><td></td></tr>').join('')}
        </tbody>
      </table>
    </div>
    ${docFooter()}`;
  openPrintWindow(html, `Traveler - ${job.poNumber}`);
}

// ── Invoice PDF ──

export function printInvoicePDF(quote: Quote, job: Job | null, settings: SystemSettings) {
  const html = `
    ${companyHeader(settings)}
    <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px">
      <div>
        <div style="font-size:24px;font-weight:800;color:#111">INVOICE</div>
        <div style="font-size:14px;color:#6b7280;margin-top:2px">Ref: ${quote.quoteNumber}</div>
      </div>
      <div style="text-align:right">
        <div style="font-size:12px;color:#6b7280">Date: ${new Date().toLocaleDateString()}</div>
        ${job ? `<div style="font-size:12px;color:#6b7280">PO: ${job.poNumber}</div>` : ''}
      </div>
    </div>
    <div style="margin-bottom:20px;padding:12px;background:#f9fafb;border-radius:8px;border:1px solid #e5e7eb">
      <div style="font-size:10px;text-transform:uppercase;color:#9ca3af;font-weight:700;margin-bottom:4px">Bill To</div>
      <div style="font-size:15px;font-weight:700">${quote.customer}</div>
      ${quote.contactName ? `<div style="font-size:12px;color:#6b7280">${quote.contactName}</div>` : ''}
    </div>
    <table>
      <thead><tr><th>Description</th><th style="text-align:right">Qty</th><th style="text-align:right">Unit Price</th><th style="text-align:right">Total</th></tr></thead>
      <tbody>
        ${quote.items.map(item => `<tr><td>${item.description}</td><td style="text-align:right">${item.qty}</td><td style="text-align:right">$${item.unitPrice.toFixed(2)}</td><td style="text-align:right;font-weight:600">$${item.total.toFixed(2)}</td></tr>`).join('')}
      </tbody>
    </table>
    <div style="display:flex;justify-content:flex-end;margin-top:16px">
      <div style="width:240px">
        <div style="display:flex;justify-content:space-between;padding:6px 0;font-size:12px"><span style="color:#6b7280">Subtotal</span><span>$${quote.subtotal.toFixed(2)}</span></div>
        ${quote.tax ? `<div style="display:flex;justify-content:space-between;padding:6px 0;font-size:12px"><span style="color:#6b7280">Tax</span><span>$${quote.tax.toFixed(2)}</span></div>` : ''}
        <div style="display:flex;justify-content:space-between;padding:10px 0;font-size:18px;font-weight:800;border-top:2px solid #111;margin-top:6px"><span>Amount Due</span><span>$${quote.total.toFixed(2)}</span></div>
      </div>
    </div>
    ${quote.terms ? `<div style="margin-top:20px;padding:12px;background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px"><div style="font-size:10px;text-transform:uppercase;color:#6b7280;font-weight:700;margin-bottom:4px">Terms</div><div style="font-size:11px;color:#374151">${quote.terms}</div></div>` : ''}
    ${docFooter()}`;
  openPrintWindow(html, `Invoice - ${quote.quoteNumber}`);
}
